language: python
python:
  - 3.5

cache: pip

services: postgresql

env:
  global:
    - SECRET_KEY=testsecretkeyblablabla
    - DB_NAME=travisci
    - DB_USERNAME=postgres
    - DB_PASSWORD=""
    - DB_HOST=localhost

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE $DB_NAME;" -U $DB_USERNAME
  - cd aikithoughts
  - python manage.py migrate
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage run manage.py test
  - coverage run manage.py behave

after_success:
  - coveralls

notifications:
  slack: tklarryonline:9i85rjQ8F8fGVKKYFSqMKag5
