language: python
python:
  - 3.5

services: postgresql

env:
  global:
    - SECRET_KEY=testsecretkeyblablabla
    - DB_NAME=travisci
    - DB_USERNAME=postgres
    - DB_PASSWORD=""
    - DB_HOST=localhost

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - cd aikithoughts
  - python manage.py migrate

script:
  - coverage run manage.py test

after_success:
  - coveralls --rcfile=../.coveragerc
